name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: create settings file
      run: |
        cp settings.php.sample settings.php
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kirinas:$(date +%s)
